### ISSUE TITLE
可以限制最小日期吗

### ISSUE THREAD

**Issue by wulianglaoge** [jarbozhang/taro-picker#3]
比如当前时间 17：52，最小选择只有18：00，这样

**Comment by jarbozhang** [comment]
可以使用fields字段，{mode: 'minute', fields: 10, unit: '分'}，这样当前是17:52，最小选择就是18:00。fields字段的意思可指定当前模式中间隔固定时间间断进行显示，例如只显示10分、20分、30分

**Comment by jarbozhang** [comment]
update:新版本如需实现这个功能需要用fields和offset配合，默认并不会直接定位到18:00，需要hour的offset属性设置为1，将可选时间向后推移一个小时，这样用fields：10就可以实现了
